In [26]:
import numpy as np 
np_data = np.ones((3,2))
np_data1 = np.ones((3,2,1))
print(np_data.ndim)
print(np_data)
print(np_data1)


2
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]


In [28]:
import numpy as np

In [33]:
data = np.arange(2,10)
s = data.mean()
s

5.5